name: little_eats
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_bloc: ^8.1.6
  awesome_dio_interceptor: ^1.2.0 # Network process logger (Logger interceptor), platform: All.
  async: ^2.11.0 #for making future function
  device_info_plus: ^9.0.2 # Get current device information from within the Flutter application.
  package_info_plus: ^4.0.2 # Get current device information from within the Flutter application.
  connectivity_plus: ^5.0.2 # To Check internet connectivity, platform: Alql.
  json_annotation: ^4.9.0 # Used by [json_serializable] for converting models class and json, platform: All.
  flutter_easyloading: ^3.0.5 # To show loader, platform: All.
  intl: ^0.19.0 # Date and time, platform: All.
  flutter_svg: ^2.0.10+1 # To load svg files in imageview, platform: All.
  dio: ^5.5.0+1  # Network Service (Api Calling), platform: All.
  get_storage: ^2.1.1 # To Store Key-value pair data (SharedPreference), platform: All.
  url_strategy: ^0.2.0 # to change url strategy, platform: All.
  permission_handler: ^11.3.1 # To request permissions, platform: Android, IOS, Windows.
  logger: ^2.3.0 # print some text in console in different styles, platform: All.
  get_it: ^7.7.0
  auto_route: 8.2.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  path_provider: ^2.1.3
  sentry_flutter: ^8.4.0
  firebase_core: ^3.1.1
  firebase_remote_config: ^5.0.2
  url_launcher: ^6.3.0
  sentry_logging: ^8.3.0
  sentry_dio: ^8.3.0
  awesome_notifications: ^0.9.3+1 
  firebase_messaging: ^15.0.2
  universal_html: ^2.2.4
  video_player: ^2.9.2
  chucker_flutter: ^1.7.2
  dots_indicator:
  table_calendar: ^3.0.9
  webview_flutter: ^4.0.1
  syncfusion_flutter_datepicker: ^27.1.57
  firebase_auth:
  pin_code_fields: ^8.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2 # To perform lint operations
  build_runner: ^2.4.8 # To Run build runner command
  flutter_gen_runner: ^5.3.1 # To Generate assets path as class formats
  json_serializable: ^6.7.1 # Generate model class using json
  auto_route_generator: ^8.0.0
  encrypt: ^5.0.1
  shimmer: ^3.0.0

flutter_gen:
  integrations:
    flutter_svg: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/svgs/
    - assets/webp/
    - assets/json/
    - assets/mp4/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-ExtraBold.ttf
          weight: 300
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/DMSans-SemiBold.ttf
          weight: 600

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
